# Generated by Django 5.1.6 on 2025-03-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(default=2, max_length=15),
            preserve_default=False,
        ),
    ]
