# Generated by Django 5.1.6 on 2025-03-10 06:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0003_tokenmodel_remove_teacher_phone_grouphomework_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('descriptions', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('descriptions', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='group',
            name='subject',
        ),
        migrations.AlterModelOptions(
            name='group',
            options={},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tabletype',
            options={},
        ),
        migrations.RenameField(
            model_name='table',
            old_name='finish_time',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_user',
            new_name='is_student',
        ),
        migrations.RemoveField(
            model_name='group',
            name='active',
        ),
        migrations.RemoveField(
            model_name='group',
            name='description',
        ),
        migrations.RemoveField(
            model_name='group',
            name='worker',
        ),
        migrations.RemoveField(
            model_name='table',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tabletype',
            name='description',
        ),
        migrations.AddField(
            model_name='group',
            name='course',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.RESTRICT, to='app_user.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='descriptions',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='price',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ManyToManyField(related_name='teacher', to='app_user.teacher'),
        ),
        migrations.AddField(
            model_name='group',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='table',
            name='descriptions',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tabletype',
            name='descriptions',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='app_user.table'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_user.tabletype'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '998900404001'. Up to 14 digits allowed.", regex='^\\+?1?\\d{9,14}$')]),
        ),
        migrations.AlterField(
            model_name='table',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_user.rooms'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
