# Generated by Django 5.1.6 on 2025-03-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0004_day_rooms_remove_group_subject_alter_group_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ManyToManyField(related_name='student', to='app_user.group'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='course',
            field=models.ManyToManyField(related_name='teacher', to='app_user.course'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='departments',
            field=models.ManyToManyField(related_name='teacher', to='app_user.departments'),
        ),
    ]
